project:
  type: website
  output-dir: _site
  pre-render: scripts/optimize-images.sh

website:
  site-url: https://maxdrohde.github.io/travel-blog/
  title: "Travel Blog"
  navbar:
    background: none
    collapse: false
    left: []

format:
  html:
    theme:
      light:
        - default
        - styles/moving.scss
      dark:
        - darkly
        - styles/moving-dark.scss
    css: styles/styles.css
    lightbox:
      match: auto
      effect: none
    toc: false
    image-lazy-loading: true
    mainfont: "IBM Plex Sans, sans-serif"
    fontsize: 16px
    linestretch: 1.4
    max-width: 1000px
    include-in-header:
      text: |
        <link rel="preconnect" href="https://images.unsplash.com">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700&family=IBM+Plex+Sans:ital,wght@0,400;0,700;1,400&family=IBM+Plex+Mono:wght@400&display=swap" rel="stylesheet">
        <link rel="dns-prefetch" href="https://images.unsplash.com">
